
version: '3.9'

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      command: start-dev
      environment:
        KC_DB: postgres
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: password
        KC_DB_URL: jdbc:postgresql://postgres/keycloak
        KC_HOSTNAME: localhost
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
      ports:
        - 8180:8080
      depends_on:
        - postgres
volumes:
  postgres_data:
    driver: local
