apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-front-deployment
  labels:
    app: task-manager-front
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: task-manager-front
  template:
    metadata:
      labels:
        app: task-manager-front
    spec:
      serviceAccountName: api-reader
      containers:
      - name: task-manager-front
        image: TASK_MANAGER_FRONT_DOCKER_IMAGE_ADDRESS
        ports:
        - containerPort: 8766
      imagePullSecrets:
      - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: task-manager-front-service
spec:
  selector:
    app: task-manager-front
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8766
      targetPort: 8766

