apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-deployment
  labels:
    app: task-manager
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: task-manager
  template:
    metadata:
      labels:
        app: task-manager
    spec:
      serviceAccountName: api-reader
      containers:
      - name: task-manager
        image: TASK_MANAGER_DOCKER_IMAGE_ADDRESS
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: task-manager-service
spec:
  selector:
    app: task-manager
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 8080

